server:
  port: 8888
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: spring-ai-mall-order-mcp-client
  main:
    web-application-type: none
  ai:
    dashscope:
      api-key: sk-0ee0d2e3da1f4071a7fd2c48f4043d52
    mcp:
      client:
        toolcallback:
          enabled: true
        sse:
          connections:
            server1:
              url: http://localhost:9000/
  mandatory-file-encoding: UTF-8

logging:
  level:
    io:
      modelcontextprotocol:
        client: DEBUG
        spec: DEBUG

ai:
  user:
    input: ????????
